let tituloDelCurso = 'Desarrollador Full Stack';
let cantidadDeAlumnos = 24;
let profesor1 = 'Nico';
let profesor2 = 'Estefi';
let alumnosAprobados = undefined;
let clasesDinamicas = true;
console.log('Titulo del curso: ' + tituloDelCurso);
console.log('Cantidad de alumnos: ' + cantidadDeAlumnos);
console.log('Profesor 1: ' + profesor1);
console.log('Profesor 2: ' + profesor2);
console.log('Alumnos aprobados: ' + alumnosAprobados);
console.log('Clases dinamicas: ' + clasesDinamicas);
console.log('Titulo del curso: ' + typeof tituloDelCurso);
console.log('Cantidad de alumnos: ' + typeof cantidadDeAlumnos);
console.log('Profesor 1: ' + typeof profesor1);
console.log('Profesor 2: ' + typeof profesor2);
console.log('Alumnos aprobados: ' + typeof alumnosAprobados);
console.log('Clases dinamicas: ' + typeof clasesDinamicas);